/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthSelectTypeCard: typeof import('./components/features/auth/AuthSelectTypeCard.vue')['default']
    BaseColumn: typeof import('./components/shared/BaseColumn.vue')['default']
    BaseContainer: typeof import('./components/shared/BaseContainer.vue')['default']
    BuildingObjectContact: typeof import('./components/features/building_object/BuildingObjectContact.vue')['default']
    BuildingObjectDahboardCard: typeof import('./components/features/building_object/BuildingObjectDahboardCard.vue')['default']
    BuildingObjectGanttChart: typeof import('./components/features/building_object/BuildingObjectGanttChart.vue')['default']
    HomeObjectCard: typeof import('./components/features/home/HomeObjectCard.vue')['default']
    HomeSearch: typeof import('./components/features/home/HomeSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/shared/SideBar.vue')['default']
  }
}
