/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/sign-up': RouteRecordInfo<'/auth/sign-up', '/auth/sign-up', Record<never, never>, Record<never, never>>,
    '/building-object/[id]/': RouteRecordInfo<'/building-object/[id]/', '/building-object/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/building-object/[id]/detail/checklist': RouteRecordInfo<'/building-object/[id]/detail/checklist', '/building-object/:id/detail/checklist', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/building-object/[id]/detail/schedule': RouteRecordInfo<'/building-object/[id]/detail/schedule', '/building-object/:id/detail/schedule', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/building-object/[id]/detail/violations': RouteRecordInfo<'/building-object/[id]/detail/violations', '/building-object/:id/detail/violations', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/options': RouteRecordInfo<'/options', '/options', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/index.vue': {
      routes: '/auth/'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/auth/sign-up.vue': {
      routes: '/auth/sign-up'
      views: never
    }
    'src/pages/building-object/[id]/index.vue': {
      routes: '/building-object/[id]/'
      views: never
    }
    'src/pages/building-object/[id]/detail/checklist.vue': {
      routes: '/building-object/[id]/detail/checklist'
      views: never
    }
    'src/pages/building-object/[id]/detail/schedule.vue': {
      routes: '/building-object/[id]/detail/schedule'
      views: never
    }
    'src/pages/building-object/[id]/detail/violations.vue': {
      routes: '/building-object/[id]/detail/violations'
      views: never
    }
    'src/pages/options.vue': {
      routes: '/options'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
